### ISSUE TITLE
Samourai vs Joinstr

### ISSUE THREAD

**Issue by kristapsk** [nopara73/Dumplings#15]
This example of Joinstr coinjoin from [here](https://stacker.news/items/247580) looks very similar to possible Samourai coinjoins - just five equal inputs, five equal outputs, no change.

![image](https://github.com/nopara73/Dumplings/assets/4500994/1a8668da-c89f-4f1f-8da0-26e4168bd3d7)

I don't know precise algorithm Dumplings uses for Samourai coinjoin detection, but somebody with better knowledge of this code could take a look and make sure these aren't counted as Samourai coinjoins.

Joinstr code is here - https://gitlab.com/1440000bytes/joinstr.

**Comment by nopara73** [comment]
Thanks for the note, I'll keep an eye on it. For now, I'd like to note I'm pretty sure the TX0 OP_RETURN is also included in the criteria, but even if it wouldn't, the amount of false positives is insignificant currently, so won't bother to check :)

**Comment by fubyo** [comment]
In the samurai mixes, only one or two of the inputs will provide the mining fee. In this mix, all the inputs gets equally feed.

**Comment by nopara73** [comment]
In that case we're good.

**Comment by kristapsk** [comment]
> In that case we're good.

Wouldn't it make sense to distinguish between Otheri and Jonstri?

**Comment by nopara73** [comment]
Yup. 

Also, since we're at it, the otheri should be removed. It gives absolutely no information to anyone. It's just a failed attempt to identify joinmarket transactions and when I realized I couldn't, then I salvaged the code by calling it "otheri."
