### ISSUE TITLE
Inaccurate statement regarding Samourai Xpubs

### ISSUE THREAD

**Issue by 6102bitcoin** [nopara73/Dumplings#2]
> Samourai CoinJoins aren't trustless either, as these companies know your xpub, from which all your present, past and future Bitcoin addresses can be derived, thus users gain no privacy against these companies and the third parties they share your data with, even if they CoinJoin.

Using dojo users don't submit their xpubs to Samourai therefore this statement is inaccurate.

**Comment by nopara73** [comment]
Take the statement: "Electrum is a light wallet."

Is this an inaccurate statement, because you can also make it a full node with @chris-belcher's Electrum Personal Server?

**Comment by 6102bitcoin** [comment]
You made a factually inaccurate statement. 

> these companies know your xpub

I am connected to my samourai DOJO so they don't know my xpub, so your statement is false. 

You are conflating trustlessness (which relates to ability to spend bitcoin) with privacy.

**Comment by nopara73** [comment]
How would you improve on it in a way that doesn't hurt anyone's feelings yet it communicates to the user the risk of using a trusted third party?

**Comment by ghost** [comment]
call it `per default, the user leaks his xpub to the company`, and be done with it. 
This is not in the scope of this research anyhow.

**Comment by 6102bitcoin** [comment]
@nopara73 this isn't about 'feelings', its about not intentionally misleading people.

The whole section is not relevant to the analysis - I would remove it

**Comment by nopara73** [comment]
When such comparisons are made this is the single most relevant information any user should need to know about. Everything else is just detail in comparison.
