### ISSUE TITLE
Bitcoin Knots vs Bitcoin Core

### ISSUE THREAD

**Issue by prusnak** [nopara73/Dumplings#7]
The [README.md](https://github.com/nopara73/Dumplings/blob/master/README.md) mentions Bitcoin Knots, but does not mention what is the specific reason to use Bitcoin Knots and not the upstream Bitcoin Core?

ISTM that Bitcoin Core should work too, but maybe I am missing something?

**Comment by ghost** [comment]
As far as I know, Core works too.

**Comment by prusnak** [comment]
Yeah, that's my observation too.

**Comment by nopara73** [comment]
Did you test it? The reason why I used Knots was that only it did give me the input scripts and amounts when asking for a block. IIRC it has been implemented in Core by Kimi, but I'd assume the API is different?

**Comment by prusnak** [comment]
@nopara73 I am running this now with Bitcoin Core 24.0.0rc3 and so far no failures.

It seems the API is the same (`getblock <blockhash> 3`) where 3 stands for `verbosity = 3`.

This is the excerpt from Bitcoin Core help:

<img width="1072" alt="Screenshot 2022-11-18 at 12 28 31" src="https://user-images.githubusercontent.com/42201/202695327-66978c76-e69b-46ff-8a63-64eff1e620a6.png">

@kiminuo Can you confirm the API is indeed the same between Knots and Core? It seems to me that it is.

Edit: here are the PRs to the Bitcoin Core: https://github.com/bitcoin/bitcoin/pull/22918 + https://github.com/bitcoin/bitcoin/pull/23320 so this means the feature is available since Bitcoin Core version 23.0

**Comment by kiminuo** [comment]
AFAIK the API is the same. There were only minor changes to the PR that I did that should not affect the functionality required by Dumplings (or any other application I believe).

**Comment by prusnak** [comment]
Thanks for the confirmation. Added PR https://github.com/nopara73/Dumplings/pull/9 which modifies not only the ReadMe but also the code and logger output.
